//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Game
{
	public enum BlockGenerateType
	{
		Blank = 1001,
		Random = 1002,
		Custom = 0,
	}

	public enum BlockItemType
	{
		Blank = 1001,
		Attack = 1002,
		Skill = 1003,
	}

	public static class EnumExtension
	{
		public static int ToInt( this BlockGenerateType type )
		{
			return (int)type;
		}

		public static int ToInt( this BlockItemType type )
		{
			return (int)type;
		}
	};

}

