//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Game
{
	public enum BlockSettingType
	{
		Random = 0,
		Fixed,
	};

	public enum BlockGenerateType
	{
		Blank = 0,
		TypeA = 1,
		TypeB = 2,
		TypeC = 3,
		TypeD = 4,
		TypeE = 5,
		Random = 6,
	}

	public enum BlockItemType
	{
		Blank,
		Attack,
		Skill,
	}

	public static class EnumExtension
	{
		public static int ToInt( this BlockGenerateType type )
		{
			return (int)type;
		}

		public static int ToInt( this BlockItemType type )
		{
			return (int)type;
		}
	};

}

