//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using UnityEngine;

namespace Utility
{
	public class CSVReader
	{
		public delegate void LineStart( int line, string[] items );
		public delegate void LineParse( int index, int line, string item );
		public delegate void LineEnd();

		public CSVReader ()
		{
		}

		public void Load( string path, LineStart start, LineParse parse, LineEnd end )
		{
			int line 	= 0;
			StreamReader reader = new StreamReader( path );
			while( false == reader.EndOfStream )
			{
				string[] items = reader.ReadLine ().Split( ',' );

				start( line, items );
				
				for( int index = 0; index < items.Length; ++index )
				{
					parse( line, index, items[ index ] );
				}

				end();

				++line;
			}

			reader.Close();
		}
	}
}

