//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

namespace Unnamed
{
	public class GUIHelper
	{
		public static bool ImageUVButton( Rect rect, Texture2D texture, Rect UV )
		{
			bool isPress = GUI.Button (rect, "" );

			if( null != texture )
			{
				Rect smallSize = GetSmallRect(rect);

				GUI.DrawTextureWithTexCoords( smallSize, texture, UV );
			}

			return isPress;
		}

		public static Rect GetSmallRect(Rect rect)
		{
			float x = rect.width * 0.05f;
			float y = rect.height * 0.05f;
			
			rect.x += x;
			rect.y += x;
			rect.xMax -= y * 2;
			rect.yMax -= y * 2;

			return rect;
		}
	}
}

