//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;

using System.Collections.Generic;

using Unnamed;

namespace BoardEditor
{
	public class AtlasSelectorWizard : ScriptableWizard
	{
//		public delegate void SelectDelegate(GameObject selected );

		private Action<GameObject> m_delegate;
		private TextureAtlas[] m_atlas;
		private Vector2 m_scrollPos = Vector2.zero;

		public AtlasSelectorWizard ()
		{
		}

		public static void ShowWizard( Action<GameObject> selectDelegate)
		{
			AtlasSelectorWizard wizard = ScriptableWizard.DisplayWizard<AtlasSelectorWizard>("Atlas selector");
			wizard.m_delegate = selectDelegate;
			wizard.minSize = wizard.maxSize = new Vector2( 256, 768 );
			wizard.m_atlas = Resources.FindObjectsOfTypeAll(typeof(TextureAtlas)) as TextureAtlas[];
		}

		void OnWizardUpdate()
		{

		}

		void OnGUI()
		{
			m_scrollPos = EditorGUILayout.BeginScrollView(m_scrollPos);
			for( int i = 0; i < m_atlas.Length; ++i )
			{
				GUILayout.Label(m_atlas[i].name);
				if(GUILayout.Button (new GUIContent(m_atlas[i].TargetTexture), GUILayout.Width (230), GUILayout.Height (230) ) )
				{
					m_delegate(m_atlas[i].gameObject);

					Close ();
				}
				EditorGUILayout.Separator();
			}

			EditorGUILayout.EndScrollView();

		}

		void Collect()
		{
		}
	}
}

