//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;
using UnityEditor;

using Unnamed;

using Game;
using Game.Data;

namespace BoardEditor
{
	public class BlockWizard : ScriptableWizard
	{
		GameObject m_prefab = null;
		BlockDataSet m_dataset = null;

		string m_savePath = "";
		string m_blockSetName = "New block set";

		public BlockWizard ()
		{
		}

		[MenuItem("Assets/" + Named.Title + "/Block Editor")]
		static void OpenEditor()
		{
			GameObject targetObject = UnityEditor.Selection.activeObject as GameObject;
			if( null == targetObject || null == targetObject.GetComponent<BlockDataSet>() )
			{
				ShowWizard(null, Path.GetSelectionPath());
			}
			else
			{
				ShowWizard(targetObject, Path.GetSelectionPath());
			}

		}

		static void ShowWizard(GameObject prefab, string savePath)
		{
			BlockWizard blockWizard = DisplayWizard<BlockWizard>("Block Editor");
			blockWizard.minSize = blockWizard.maxSize = new Vector2(200, 840);
			blockWizard.m_savePath = savePath;
			blockWizard.m_prefab = prefab;
			if( null != prefab )
			{
				blockWizard.m_blockSetName = prefab.name;
				blockWizard.m_dataset = prefab.GetComponent<BlockDataSet>();
			}
		}

		void OnGUI()
		{
			EditorGUILayout.LabelField("Block Editor");

			m_blockSetName = EditorGUILayout.TextField( m_blockSetName );

			if( GUILayout.Button ("Create block set"))
			{
				string finalPath = AssetDatabaseHelper.MakePrefabPath(m_savePath, m_blockSetName);

				bool isContinue = true;
				if( true == AssetDatabaseHelper.IsExistAsset(finalPath) )
				{
					isContinue = EditorUtility.DisplayDialog("", "이대로 저장하면 기존 데이터를 덮어씁니다. 계속하시겠습니까?", "예", "아니오");
				}

				if( true == isContinue )
				{
					GameObject prefab = new GameObject(m_blockSetName);
					prefab.AddComponent<BlockDataSet>().name = m_blockSetName;

					m_prefab = AssetDatabaseHelper.CreatePrefab(finalPath, prefab);

					GameObject.DestroyImmediate(prefab);

					m_dataset = m_prefab.GetComponent<BlockDataSet>();

				}
			}

			if( null == m_prefab )
			{
				return ;
			}

			if( GUILayout.Button ("Save block set"))
			{

				EditorUtility.SetDirty(m_prefab);
				
				AssetDatabase.SaveAssets();
				AssetDatabase.Refresh();

			}

			bool isSelected = false;
			if( null == m_dataset.Atlas )
			{
				isSelected = GUILayout.Button ("Select atlas", GUILayout.Width (190), GUILayout.Height (190));
			}
			else
			{
				isSelected = GUILayout.Button (new GUIContent(m_dataset.Atlas.TargetTexture), GUILayout.Width (190), GUILayout.Height (190));
			}

			if(true == isSelected)
			{
				Action<GameObject> selectCallback = (GameObject atlas)=>
				{
					TextureAtlas textureAtlas = atlas.GetComponent<TextureAtlas>();
					m_dataset.Atlas = textureAtlas;

					Repaint();
				};

				AtlasSelectorWizard.ShowWizard(selectCallback);
			}

			//max 400
			Rect windowPosition = new Rect(5, 300, 190, 80 );

			BeginWindows();
			GUI.Window (0, windowPosition, Blank, "Blank" );

			windowPosition.y += windowPosition.height + 10;
			GUI.Window ((int)BlockType.TypeA, windowPosition, Blocks, "AType" );

			windowPosition.y += windowPosition.height + 10;
			GUI.Window ((int)BlockType.TypeB, windowPosition, Blocks, "BType" );

			windowPosition.y += windowPosition.height + 10;
			GUI.Window ((int)BlockType.TypeC, windowPosition, Blocks, "CType" );

			windowPosition.y += windowPosition.height + 10;
			GUI.Window ((int)BlockType.TypeD, windowPosition, Blocks, "DType" );

			windowPosition.y += windowPosition.height + 10;
			GUI.Window ((int)BlockType.TypeE, windowPosition, Blocks, "EType" );

			EndWindows ();
		
		}

		void Blank(int id) 
		{
			if( ImageButton(new Rect( 5, 22, 50, 50 ), "Blank", m_dataset.Atlas, BlockCode.Blank) )
			{
				Action<TextureAtlas.Atlas> action = (TextureAtlas.Atlas atlas) =>
				{
					this.AddOrReplace(BlockCode.Blank, atlas.name);

					Repaint ();
				};

				SpriteSelectorWizard.ShowWizard( m_dataset.Atlas, action );
			}
		}

		void Blocks( int blockType )
		{
			string[] subName = { "SubA", "SubB", "SubC" };

			for( int codeIndex = 0; codeIndex < BlockConst.SubCount; ++codeIndex )
			{

				BlockCode blockCode = ((BlockType)blockType).ToBlockCode(codeIndex);

				//15는 사이간격.
				float left = 5 + ( codeIndex * 15 ) + ( codeIndex * 50);
				if( ImageButton(new Rect( left, 22, 50, 50 ), subName[codeIndex], m_dataset.Atlas, (BlockCode)blockCode) )
				{
					Action<TextureAtlas.Atlas> action = (TextureAtlas.Atlas atlas) =>
					{
						this.AddOrReplace(blockCode, atlas.name);
						
						Repaint ();
					};
					
					SpriteSelectorWizard.ShowWizard( m_dataset.Atlas, action );
				}
			}
		}

		void AddOrReplace(BlockCode code, string name)
		{
			BlockDataSet.KeyValue keyValue = this.FindDataByCode(code);

			if( null == keyValue )
			{
				m_dataset.Data.Add (new BlockDataSet.KeyValue(code,name));
			}
			else
			{
				keyValue.name = name;
			}
		}

		bool ImageButton(Rect pos, string name, TextureAtlas atlas, BlockCode code )
		{
			bool isPress = false;
			BlockDataSet.KeyValue keyValue = this.FindDataByCode(code);
			if( null == keyValue )
			{
				isPress = GUI.Button (pos, name );
			}
			else
			{
				TextureAtlas.Atlas sprite = atlas.GetAtlasByName( keyValue.name );
				if( null != sprite )
				{
					isPress = ButtonHelper.ImageUVButton( pos, atlas.TargetTexture, sprite.UV );
				}
			}

			return isPress;
		}

		public BlockDataSet.KeyValue FindDataByCode( BlockCode code )
		{
			if( null == m_dataset )
			{
				return null;
			}

			foreach( BlockDataSet.KeyValue kv in m_dataset.Data )
			{
				if( kv.code == code )
				{
					return kv;
				}
			}

			return null;
		}
	}
}

