//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;

namespace BoardEditor
{
	public class BoardEditorSettingWizard : ScriptableWizard
	{
		public const string SetHexDefWidth = "Hex_DefWidth";
		public const string SetHexDefHeight = "Hex_DefHeight";
		public const string SetHexDefPixel = "Hex_DefPixel";

		int defaultWidth;
		int defaultHeight;
		int defaultPixel;

		public BoardEditorSettingWizard ()
		{
		}

		public static void ShowWizard()
		{
			BoardEditorSettingWizard wizard = ScriptableWizard.DisplayWizard<BoardEditorSettingWizard>("Setting");
			wizard.minSize = wizard.maxSize = new UnityEngine.Vector2( 256, 512 );
			wizard.defaultWidth = BoardEditorSettingWizard.GetHexDefWidth();
			wizard.defaultHeight = BoardEditorSettingWizard.GetHexDefHeight();
			wizard.defaultPixel = BoardEditorSettingWizard.GetHexDefPixel();
		}

		void OnGUI()
		{
			EditorGUILayout.LabelField("Board settings" );

			defaultWidth = EditorGUILayout.IntField ( "Default Width", defaultWidth );
			defaultHeight = EditorGUILayout.IntField ( "Default Height", defaultHeight );
			defaultPixel = EditorGUILayout.IntField ( "Default Pixel", defaultPixel );

			if( GUILayout.Button ("Apply") )
			{
				EditorPrefs.SetInt (SetHexDefWidth, defaultWidth);
				EditorPrefs.SetInt (SetHexDefHeight, defaultHeight);
				EditorPrefs.SetInt (SetHexDefPixel, defaultPixel);
			}
		}

		void OnWizardUpdate()
		{
		}

		void OnWizardCreate()
		{
		}

		static public int GetHexDefWidth()
		{
			return EditorPrefs.GetInt(SetHexDefWidth, 1000 );
		}

		static public int GetHexDefHeight()
		{
			return EditorPrefs.GetInt(SetHexDefHeight, 650 );
		}

		static public int GetHexDefPixel()
		{
			return EditorPrefs.GetInt(SetHexDefPixel, 100 );
		}
	}
}

