//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

using UnityEngine;
using UnityEditor;

namespace BoardEditor
{
	public class Setting
	{
		public const string WIDTH = "MECA_WIDTH";
		public const string HEIGHT = "MECA_HEIGHT";
		public const string PIXEL = "MECA_PIXEL";
		public const string ATLAS_PATH = "MECA_ATLASPATH";
		public const string ATLAS_SPRITECOUNT= "MECA_ATLAS_SPRITECOUNT";
		public const string ATLAS_SPRITENAME = "MECA_ATLAS_SPRITENAME";
		
		public int DefaultWidth { get; set; }
		public int DefaultHeight { get; set; }
		public int DefaultPixel { get; set; }
		public string DefaultAtlasPath { get; set; }
		public List<string> DefaultAtlasElems = new List<string>();
		
		public GameObject DefaultAtlas = null;

		public Setting ()
		{

		}

		public void Save()
		{
			EditorPrefs.SetInt (WIDTH, DefaultWidth);
			EditorPrefs.SetInt (HEIGHT, DefaultHeight);
			EditorPrefs.SetInt (PIXEL, DefaultPixel);
			EditorPrefs.SetString (ATLAS_PATH, DefaultAtlasPath);
			
			EditorPrefs.SetInt (ATLAS_SPRITECOUNT, DefaultAtlasElems.Count);
			
			for( int i = 0; i < DefaultAtlasElems.Count; ++i ) 
			{
				EditorPrefs.SetString (this.MixSpriteName(i), DefaultAtlasElems[i]);
			}
		}

		public void Load()
		{
			DefaultWidth = EditorPrefs.GetInt(WIDTH, 1000 );
			DefaultHeight = EditorPrefs.GetInt(HEIGHT, 650 );
			DefaultPixel = EditorPrefs.GetInt (PIXEL, 100 );
			DefaultAtlasPath = EditorPrefs.GetString (ATLAS_PATH, "");
			
			if( false == string.IsNullOrEmpty( DefaultAtlasPath ) )
			{
				DefaultAtlas = AssetDatabase.LoadAssetAtPath(DefaultAtlasPath, typeof(GameObject)) as GameObject;
				if( null == DefaultAtlas )
				{
					DefaultAtlasPath = "";
					DefaultAtlas = null;
				}
				else
				{
					int count = EditorPrefs.GetInt (ATLAS_SPRITECOUNT,0);
					for( int i = 0; i < count; ++i )
					{
						string keyName = this.MixSpriteName(i);
						string atlasName = EditorPrefs.GetString(keyName, "");
						if( true == string.IsNullOrEmpty(atlasName) )
						{
							continue;
						}

						DefaultAtlasElems.Add (atlasName);
					}
				}
			}
		}

		private string MixSpriteName( int index )
		{
			return ATLAS_SPRITENAME + index.ToString();
		}


	}
}

