//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

using UnityEngine;
using UnityEditor;
using Game;

namespace BoardEditor
{
	public class Setting
	{
		public const string WIDTH = "MECA_WIDTH";
		public const string HEIGHT = "MECA_HEIGHT";
		public const string PIXEL = "MECA_PIXEL";
		public const string BLOCK_SET = "MECA_BLOCKSET";
		 
		public int DefaultWidth { get; set; }
		public int DefaultHeight { get; set; }
		public int DefaultPixel { get; set; }
		public string DefaultBlockSetPath { get; set; }
		 
		public GameObject DefaultBlockSet = null;

		[MenuItem("Assets/" + Named.Title + "/Clear settings")]
		static void ClearEditorPrefs()
		{
			EditorPrefs.DeleteKey(WIDTH);
			EditorPrefs.DeleteKey(HEIGHT);
			EditorPrefs.DeleteKey(PIXEL);
			EditorPrefs.DeleteKey(BLOCK_SET);
		}

		public Setting () 
		{ 
		}

		public void Save()
		{  
			EditorPrefs.SetInt (WIDTH, DefaultWidth);
			EditorPrefs.SetInt (HEIGHT, DefaultHeight);
			EditorPrefs.SetInt (PIXEL, DefaultPixel);
			EditorPrefs.SetString (BLOCK_SET, DefaultBlockSetPath);
		}

		public void Load()
		{ 
			DefaultWidth = EditorPrefs.GetInt(WIDTH, 1000 );
			DefaultHeight = EditorPrefs.GetInt(HEIGHT, 650 );
			DefaultPixel = EditorPrefs.GetInt (PIXEL, 100 );
			DefaultBlockSetPath = EditorPrefs.GetString (BLOCK_SET, "");
			
			if( false == string.IsNullOrEmpty( DefaultBlockSetPath ) )
			{
				DefaultBlockSet = AssetDatabase.LoadAssetAtPath(DefaultBlockSetPath, typeof(GameObject)) as GameObject;
				if( null == DefaultBlockSet )
				{
					DefaultBlockSetPath = "";
					DefaultBlockSet = null;
				}
			}
		}

	}
}

