//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace UnnamedObject
{
	public enum HexagonShape
	{
		None = 0,
		RightUp,
		Right,
		RightDown,
		LeftDown,
		Left,
		LeftUp,
		Max,
	};

	public class HexagonVertex
	{
		public Vector2[] Hexagon { get; set; }

		public static float Width = 1f;
		public static float Height = 0.87f;
		public static int[] Triangles = new int[] { 0, 1, 2, 0, 2, 3, 0, 3, 4, 0, 4, 5, 0, 5, 6, 0, 6, 1 };

		public HexagonVertex ( float width, float height)
		{
			Width = width;
			Height = height;

			Hexagon = new Vector2[(int)HexagonShape.Max];
			
			this.Restore();
		}

		public void SetVertex( HexagonShape shape, Vector2 v )
		{
			Hexagon[(int)shape] = v;
		}

		public void Restore()
		{
			float halfWidth = Width * 0.5f;
			float halfWidth25 = Width * 0.25f;
			float halfHeight = Height * 0.5f;

			
			SetVertex(HexagonShape.None, Vector2.zero);
			SetVertex(HexagonShape.RightUp, new Vector2(halfWidth25, halfHeight));
			SetVertex(HexagonShape.Right, new Vector2(halfWidth, 0));
			SetVertex(HexagonShape.RightDown, new Vector2(halfWidth25, -halfHeight));
			SetVertex(HexagonShape.LeftDown, new Vector2(-halfWidth25, -halfHeight));
			SetVertex(HexagonShape.Left, new Vector2(-halfWidth, 0));
			SetVertex(HexagonShape.LeftUp, new Vector2(-halfWidth25, halfHeight));
		}

		public void SetSize( float w, float h )
		{
			Width = w;
			Height = h;

			this.Restore ();
		}

		public Vector2[] ScaleUP( float ratio)
		{
			Vector2[] scale = new Vector2[(int)HexagonShape.Max];

			for( int i = 0; i < scale.Length; ++i )
			{
				scale[i] = Hexagon[i] * ratio;
			}

			return scale;
		}
	}
}

