//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using UnityEditor;

namespace Unnamed
{
	public class AssetDatabaseHelper
	{
		public static GameObject CreatePrefab( string path, GameObject go )
		{
			Object prefab = PrefabUtility.CreateEmptyPrefab(path);
			PrefabUtility.ReplacePrefab(go, prefab);

			AssetDatabase.SaveAssets();
			AssetDatabase.Refresh();

			return AssetDatabase.LoadAssetAtPath(path, typeof(GameObject)) as GameObject;
		}

		public static string MakePrefabPath( string path, string name )
		{
			return path + "/" + name + ".prefab";
		}

		public static bool IsExistAsset( string path )
		{
			return ( null == AssetDatabase.LoadAssetAtPath(path, typeof(Object)) ) ? false : true;
		}

		public static T LoadAsset<T>(string path) where T : class
		{
			return AssetDatabase.LoadAssetAtPath(path, typeof(T)) as T;
		}
	}
}

