//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Utility
{
	public class BitValue
	{
		private int m_value { get; set; }

		public BitValue()
		{
			m_value = 0;
		}

		public void Set( int bit )
		{
			m_value = bit;
		}

		public int Get()
		{
			return m_value;
		}

		public void Add( int bit )
		{
			m_value |= bit;
		}

		public void Sub( int bit )
		{
			m_value &= ~bit;
		}

		public void AddOffset( int off )
		{
			m_value |= 1 << off;
		}

		public void SubOffset( int off )
		{
			m_value &= ~ ( 1 << off );
		}

		public bool IsAnd( int bit )
		{
			return true == ( 0 != ( m_value & bit ) );
		}


	}
}

