//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Unnamed
{
	public class Display : MonoBehaviour
	{
		public static float WidthRatio = 16.0f;
		public static float HeightRatio = 9.0f;

		public Display ()
		{
		}

		void Awake()
		{
			BuildCamera();
		}

		public static void BuildCamera()
		{
			Camera[] allCameras = Camera.allCameras;
			foreach (Camera currentCamera in allCameras)
			{
				float newAspectRatio = WidthRatio / HeightRatio;
				
				float variance = newAspectRatio / currentCamera.aspect;
				if (variance < 1.0f)
				{
					currentCamera.rect = new Rect((1.0f - variance) / 2.0f, 0, variance, 1.0f);
				}
				else
				{
					variance = 1.0f / variance;
					
					currentCamera.rect = new Rect(0, (1.0f - variance) / 2.0f, 1.0f, variance);
				}
			}
		}
	}
}

