//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18408
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace UnnamedUtility
{
		public static class NumberExtensions
		{
			static public float Center ( this float value, float subValue )
			{
				return ( value - subValue ) * 0.5f;
			}

			static public int Center ( this int value, int subValue )
			{
				return (int)((( value - subValue ) * 0.5f)+0.5f);
			}
		}
}

